### ISSUE TITLE
Sources for bundles from Eclipse Orbit are not downloaded

### ISSUE THREAD

**Issue by fbricon** [fbricon/pde.source.lookup#1]
- Add org.apache.commons.jxpath (or any other jar from Orbit apparently) to a plugin project's MANIFEST.MF
- open a class from org.apache.commons.jxpath, no source is found

the artifactRepository manager fails to find any match to the given source ArtifactKey.

`artifactRepo.query(new ArtifactKeyQuery(sourceKey), monitor)` returns a result (i.e the matching sourceKey) for:  
- http://download.eclipse.org/releases/staging/, 
- http://download.eclipse.org/tools/orbit/downloads/drops/R20150821153341/repository/ , 
- http://download.eclipse.org/tools/orbit/downloads/drops/S20160308060251/repository/, 

but then [`artifactRepo.contains(sourceKey)`](https://github.com/fbricon/pde.source.lookup/blob/master/org.jboss.tools.pde.sourcelookup.ui/src/main/java/org/jboss/tools/pde/sourcelookup/ui/internal/jobs/P2SourceDownloadJob.java#L147) returns false.

Something's odd here. @prapicault, @irbull any ideas?

**Comment by rgrunber** [comment]
I think I see the issue. Each Orbit artifact has 2 versions. A packed (.jar.pack.gz), and a regular (.jar) and they will return from the same artifact key query. We should probably further restrict our search to artifacts whose descriptor has no "format" key set to "packed" in the properties.

**Comment by fbricon** [comment]
I have no idea on how to do that

**Comment by rgrunber** [comment]
I'll push something. In fact it seems p2 takes care of the unpacking so I would say its safe to take any matching artifact.

**Comment by rgrunber** [comment]
As a note, although this seems to work, I've found some other issues when the source has already been fetched locally and all that's necessary is for the source attachment to execute, so there might be a bug in there as well. I might look into it if I get some time.

**Comment by fbricon** [comment]
Nice catch @rgrunber! One small change having a big impact :-)

So it mostly works, but I've also seen a couple cases that are not working:
- any jar from under org.apache.ant_xyz/lib are not considered bundles (ant-*.jar)
- org.apache.aries.spifly.dynamic.bundle_1.0.2.jar, org.apache.aries.util_1.1.1.jar have no sources, not sure if they're actually source-less or not

**Comment by fbricon** [comment]
so as I mentioned already, on workspace restart any previous source attachment is reset. That's likely a PDE bug/feature
