### ISSUE TITLE
Is this about a bug in PDE?

### ISSUE THREAD

**Issue by mickaelistria** [fbricon/pde.source.lookup#12]
The description says "Because the Plug-in Dependencies classpath container doesn't keep new attached sources on workspace restart". Is this a bug on PDE? Is this reported? If all this user story can be covered by fixing a bug, it seems leaner than having a bunch of additional plugins to install.

**Comment by fbricon** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=492204

**Comment by mickaelistria** [comment]
Closing as this is already reported and there is nothing more to discuss here.
